cli/rustfs-gui/src/components/home.rs
We should always use English in the code.
=> chore: translate to English

README.md, README_ZH.md
=> fix video url error

crates/ecstore/src/cmd/bucket_targets.rs, rustfs/src/admin/handlers.rs
=> remove target return 204

.github/workflows/build.yml, .github/workflows/docker.yml
=> fix: github flow

.cursorrules, .github/workflows/build.yml, .github/workflows/docker.yml
This PR enhances the build and release workflow to support multi-platform builds and improve the release process with comprehensive GitHub CLI integration.
- **Expanded target platforms**: Linux (x86_64, ARM64), macOS (Apple Silicon, Intel), Windows (x86_64, ARM64)
- **Static binaries for Linux**: Using musl targets for better compatibility
- **Cross-compilation support**: zigbuild for Linux ARM64, cross for Windows ARM64
- **GitHub CLI integration**: Replaced GitHub Actions with native `gh` commands
- **Automatic asset packaging**: Platform-specific archives (.tar.gz for Unix, .zip for Windows)
- **Checksum generation**: SHA256 and SHA512 hashes for all binaries
- **Professional release notes**: Installation guides, verification instructions, platform compatibility
- **Desktop GUI …
=> feat: enhance build and release workflow with multi-platform support

Dockerfile
=> fix unzip error

crates/ecstore/src/disk/local.rs, crates/ecstore/src/store.rs
=> fix: troubleshooting startup failure in Windows System

crates/iam/src/store/object.rs
=> fix(iam):decrypt_data failed when password changed

.github/actions/setup/action.yml, .github/workflows/ci.yml
The previous cache configuration does not take effect.
This PR fixes the bug in CI workflow.
=> ci: fix cache

rustfs/src/admin/handlers/bucket_meta.rs, rustfs/src/admin/handlers/event.rs, rustfs/src/admin/handlers/group.rs, rustfs/src/admin/handlers/policys.rs, rustfs/src/admin/handlers/rebalance.rs, rustfs/src/admin/handlers/service_account.rs, rustfs/src/admin/handlers/tier.rs, rustfs/src/admin/handlers/user.rs
Add Content-Length headers to all admin API endpoints that return empty response bodies to ensure HTTP response completeness and standard compliance.
- `rustfs/src/admin/handlers/bucket_meta.rs` - Add Content-Length header for ImportBucketMetadata operation
- `rustfs/src/admin/handlers/event.rs` - Add Content-Length headers for event-related operations
- `rustfs/src/admin/handlers/group.rs` - Add Content-Length headers for group management operations
- `rustfs/src/admin/handlers/policys.rs` - Add Content-Length headers for policy management operations
- `rustfs/src/admin/handlers/rebalance.rs` - Add Content-Length header for rebalance operations
- `rustfs/src/admin/handlers/service_account.rs` - Add Content-Length headers for service account operations
- …
=> feat: add Content-Length headers to admin API responses

.github/workflows/docker.yml
Docker builds were failing with 401 Unauthorized errors when pulling base images (`alpine:3.18` and `rust:1.85-alpine`) during multi-platform builds, despite successful Docker Hub authentication.
The issue was caused by authentication not being properly propagated to all build contexts during multi-platform builds with Docker buildx.
This PR implements a comprehensive fix for Docker Hub authentication issues:
- Configure `docker-container` driver for better authentication handling
- Add Docker Hub registry mirrors for improved reliability
- Implement proper authentication verification
- Add comprehensive authentication testing before builds
- Test base image access to verify credentials
- Bootstrap buildx builder with proper configuration
- Implement retry logic with …
=> fix: resolve Docker Hub authentication issues in multi-platform builds

.cursorrules
This PR significantly enhances the cursor rules to provide the strictest possible protection against direct commits to the main branch.
- **🚨 Added zero-tolerance policy**: Absolute prohibition of direct commits to main/master branch
- **🔥 Strengthened enforcement**: Clear consequences for violations (immediate reversal)
- **🚫 Eliminated all exceptions**: No exceptions for hotfixes, emergencies, small changes, or anyone
- **📋 Detailed mandatory workflow**: Step-by-step process that must be followed
- **🔒 Listed enforcement mechanisms**: Branch protection, pre-commit hooks, CI/CD checks
1. **More prominent warnings**: Added multiple warning levels and emojis for visibility
2. **Zero tolerance language**: Made it clear that there are absolutely no exceptions
3. **Detailed workflow steps**: …
=> feat: enhance cursor rules with strict main branch protection

.docker/alpine/Dockerfile.prebuild, .docker/ubuntu/Dockerfile.prebuild, .github/workflows/build.yml, .github/workflows/docker.yml, Dockerfile
This PR addresses the critical build dependency issue where Docker builds could fail when expected binary artifacts don't exist, especially during manual workflow triggers.
- Added  input parameter to  workflow_dispatch
- Default value:  (always available)
- Supported formats:
-  - Latest stable release
-  - Latest development build from main branch
-  - Specific release version
-  - Specific development build
- Modified  to create  versions for main branch builds
- Ensures Docker builds always have a reliable fallback version
- Creates both platform-specific and generic main-latest artifacts
- Eliminated unpredictable source-build fallbacks from all Dockerfile variants
- Docker builds now **fail fast** with clear error messages
- Added helpful guidance for users when builds fail
- Clear, …
=> feat: Improve Docker build with version selection and remove fallback mechanism

Cargo.lock, Cargo.toml
Upgrade `s3s` version
https://github.com/Nugine/s3s/tree/release/minio
=> build: upgrade s3s

build-rustfs.sh
The build script fails on macOS with error: `sha256sum: command not found` because macOS doesn't have the `sha256sum` command by default.
- Added `generate_sha256()` function to handle cross-platform SHA256 generation
- Uses `shasum -a 256` on macOS instead of `sha256sum`
- Uses `sha256sum` on Linux with `shasum` as fallback
- Replaced direct `sha256sum` usage in build script with new function
- Added cross-platform SHA256 checksum generation function
- Updated build script to use the new function instead of direct `sha256sum` command
- Maintains backward compatibility and same output format
- Verified `shasum -a 256` works correctly on macOS
- Function includes proper error handling for missing commands
- Supports both Linux and macOS platforms
Fixes the build failure on macOS runners in …
=> fix: add cross-platform SHA256 checksum generation

rustfs/src/main.rs, rustfs/src/update.rs, rustfs/src/version.rs
- Improve error handling and type safety
---
=> feat: enhance version function with automatic version increment

Dockerfile.source
The Docker build for `Dockerfile.source` was failing with multiple issues:
1. **Workspace structure error**: `COPY */Cargo.toml ./*/` glob pattern doesn't work in Docker
2. **sccache wrapper error**: `RUSTC_WRAPPER=sccache` causing compilation failures
3. **Missing target error**: ARM64 target not properly installed for cross-compilation
**Simplified and More Reliable Approach:**
- **Removed complex dependency caching** - Use simple `COPY . .` for easier maintenance
- **Removed sccache completely** - Eliminate compilation wrapper issues  
- **Added target installation in build step** - Ensure targets are available when needed
- **Added debug output** - Better visibility into build process
- **Added error handling** - Proper handling for unsupported platforms
1. **Simplified COPY …
=> fix: Simplify Dockerfile.source and resolve build issues

.github/workflows/build.yml
=> fix: ossutil install command.

build-rustfs.sh, rustfs.spec
=> add rustfs.spec for rustfs

crates/s3select-api/src/lib.rs, crates/s3select-api/src/test/mod.rs, crates/s3select-api/src/test/query_execution_test.rs, crates/s3select-query/src/lib.rs, crates/s3select-query/src/test/error_handling_test.rs, crates/s3select-query/src/test/integration_test.rs, crates/s3select-query/src/test/mod.rs
=> s3Select: add unit test case

Cargo.lock, crates/e2e_test/Cargo.toml, crates/e2e_test/src/reliant/lock.rs, crates/lock/src/lib.rs, crates/lock/src/namespace.rs
=> Lock: add transactional

rustfs/src/storage/ecfs.rs
=> feat: add basic tests for core storage module

rustfs/src/admin/handlers.rs
=> feat: add tests for admin handlers module

Makefile, crates/ahm/src/scanner/data_scanner.rs
=> Fix: fix data integrity check

Cargo.lock, crates/ecstore/src/set_disk.rs
=> fix: miss inline metadata

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/checksums/src/http.rs, crates/checksums/src/lib.rs, crates/ecstore/src/bucket/object_lock/objectlock.rs, crates/ecstore/src/cmd/bucket_replication.rs, crates/ecstore/src/store_init.rs, crates/filemeta/src/filemeta.rs, crates/filemeta/src/metacache.rs, crates/rio/Cargo.toml, crates/s3select-query/src/data_source/table_source.rs, rustfs/src/admin/handlers.rs, rustfs/src/admin/handlers/event.rs, rustfs/src/admin/handlers/tier.rs, rustfs/src/admin/handlers/trace.rs, rustfs/src/auth.rs
=> fix: add tokio-test

.github/workflows/audit.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/docker.yml, .github/workflows/performance.yml, Cargo.lock, Cargo.toml
- Update GitHub Actions checkout action version
- Ensure compatibility with latest workflow features
- Maintain existing checkout behavior and configuration
---
=> chore: upgrade actions/checkout from v4 to v5

crates/ecstore/src/rpc/peer_s3_client.rs, crates/ecstore/src/store.rs, rustfs/src/storage/ecfs.rs
=> fix:make bucket exists

README.md
=> docs: update doc/docker-data-dir README.md

rustfs/src/server/http.rs
=> fix: add the default port number to the given server domains (#373)

crates/ecstore/src/config/storageclass.rs, crates/ecstore/src/set_disk.rs, rustfs/src/storage/ecfs.rs
[issue #155 ](https://github.com/rustfs/rustfs/issues/155)
---
=> Fix: add support for additional AWS S3 storage classes and validation logic

crates/ahm/src/scanner/data_scanner.rs, crates/ahm/src/scanner/node_scanner.rs, crates/ahm/tests/heal_integration_test.rs, crates/ahm/tests/lifecycle_integration_test.rs, crates/ecstore/src/data_usage.rs, crates/protos/src/main.rs, rustfs/src/admin/handlers.rs
=> Fix: fix collect usage data

crates/notify/src/notifier.rs, crates/notify/src/rules/config.rs, crates/notify/src/rules/xml_config.rs, crates/targets/src/arn.rs, rustfs/src/main.rs, rustfs/src/storage/ecfs.rs
=> add bucket notification configuration

.docker/observability/otel-collector-config.yaml, README.md, README_ZH.md
=> update docker compose usage guidence in READEME file

Cargo.lock, Cargo.toml, crates/ahm/Cargo.toml, crates/lock/Cargo.toml, crates/utils/Cargo.toml
=> remove deps

rustfs/src/main.rs
=> add startup logo

README.md, README_ZH.md, docker-compose.yml
=> add tls support for docker compose

crates/ecstore/src/set_disk.rs, crates/lock/src/fast_lock/object_pool.rs, crates/lock/src/fast_lock/shard.rs, crates/lock/src/fast_lock/state.rs, crates/utils/src/retry.rs
- Add lock timeout support and track acquisition time in lock state
- Improve lock conflict handling with detailed error messages
- Optimize lock reuse when already held by same owner
- Refactor lock state to store owner info and timeout duration
- Update all lock operations to handle new state structure
---
=> feat(lock): enhance lock management with timeout and ownership tracking

Cargo.lock, Cargo.toml, crates/e2e_test/src/kms/bucket_default_encryption_test.rs
=> fix: CompleteMultipartUpload encryption
