rustfs/rustfs

- README_ZH.md
The Getting Started link in the **README_ZH.md** is empty. Change it to match the link in the **README.md**.
> chore: quickstart link in README_ZH

- Cargo.lock
- crates/utils/src/net.rs
- rustfs/Cargo.toml
- rustfs/src/main.rs
- Change default network listen address from IPv6 (`::`) to IPv4 (`0.0.0.0`)
- Add `CatchPanicLayer` to prevent server crashes from unhandled panics
- Enable `catch-panic` feature in `tower-http` dependencies
- Update network address parsing tests to reflect IPv4 change
This change improves compatibility and stability by:
- Using IPv4 as the default listen address for better cross-platform compatibility
- Adding panic recovery middleware to handle unexpected errors gracefully
- Preventing server crashes due to unhandled panics in request processing
- Modified `crates/utils/src/net.rs` to use `Ipv4Addr::new(0, 0, 0, 0)` instead of `Ipv6Addr::UNSPECIFIED`
- Added `CatchPanicLayer` to the service stack in `rustfs/src/main.rs`
- Updated `Cargo.toml` to include `catch-panic` feature
- Updated …
> feat: change default listen to IPv4 and add panic recovery

- docker-compose.yml
**Context and Purpose:**
This PR automatically remediates a security vulnerability:
- **Description:** Service 'rustfs' allows for privilege escalation via setuid or setgid binaries. Add 'no-new-privileges:true' in 'security_opt' to prevent this.
- **Rule ID:** yaml.docker-compose.security.no-new-privileges.no-new-privileges
- **Severity:** HIGH
- **File:** docker-compose.yml
- **Lines Affected:** 19 - 19
This change is necessary to protect the application from potential security risks associated with this vulnerability.
**Solution Implemented:**
The automated remediation process has applied the necessary changes to the affected code in `docker-compose.yml` to resolve the identified issue.
Please review the changes to ensure they are correct and integrate as expected.
> Fix: Redis Service Allows Unauthorized Privilege Escalation in docker-compose.yml

- .github/actions/setup/action.yml
This pull request restores and optimizes the caching mechanism for Zig and cargo-zigbuild in the  composite action. It uses  and  to speed up cross-compilation tool installation and avoid repeated downloads.
- Use  for Zig installation with built-in caching.
- Use  for cargo-zigbuild installation and caching.
- Remove manual download and cache logic for these tools.
- All comments and code are in English.
- Greatly reduces CI build time for cross-compilation jobs.
- Ensures all workflow and code comments are in English for better maintainability.
- Follows best practices for GitHub Actions and Rust toolchain setup.
---
**Please review and merge if everything looks good.**
> fix: restore Zig and cargo-zigbuild caching in GitHub Actions setup action

- .github/workflows/build.yml
The build workflow was potentially overwriting existing release content, which could cause:
- Loss of manually edited release notes
- Duplicate release creation attempts
- Overwriting of custom release descriptions
Added intelligent checks to prevent overwriting existing release content:
- Check if release already exists before creating
- Skip creation if release is already present
- Avoid duplicate release creation errors
- Detect if release notes are manually edited
- Only update auto-generated notes
- Preserve custom user content
- Use  to check existing content
- Pattern matching to identify auto-generated notes
- Conditional updates based on content state
- ****: Added protection logic in release creation and notes update steps
- ✅ Release creation skips if already exists
- ✅ Manual …
> fix: prevent overwriting existing release content in build workflow

- README.md
Added language selection links to the README for easier access to translated versions: German, Spanish, French, Japanese, Korean, Portuguese, and Russian.
The updated links can be previewed in my forked repository: https://github.com/dowithless/rustfs/tree/patch-1
---
> doc: Add links to translated README versions

- .github/workflows/build.yml
- Improved the ossutil installation logic in the GitHub Actions workflow for both Linux and macOS platforms.
- Now uses direct download and extraction for each platform, ensuring correct binary placement and permissions.
- The previous logic was not robust and could fail in some environments.
- This change makes the workflow more reliable and explicit for each platform.
- Only the workflow file was changed. The fix will be validated by CI on PR.
---
**Please review and merge if all checks pass.**
> fix: improve ossutil install logic in GitHub Actions workflow

- .cursorrules
- Cargo.lock
- cli/rustfs-gui/Cargo.toml
- cli/rustfs-gui/src/utils/helper.rs
- crates/common/Cargo.toml
- crates/common/src/globals.rs
- crates/iam/Cargo.toml
- crates/iam/src/store/object.rs
- crates/lock/Cargo.toml
- crates/lock/src/lib.rs
- crates/s3select-query/Cargo.toml
- crates/s3select-query/src/dispatcher/manager.rs
- crates/signer/Cargo.toml
- crates/signer/src/request_signature_streaming.rs
- crates/signer/src/request_signature_v4.rs
- crates/utils/Cargo.toml
- crates/utils/src/net.rs
- crates/utils/src/string.rs
- rustfs/Cargo.toml
- rustfs/src/license.rs
- rustfs/src/storage/ecfs.rs
- rustfs/src/storage/options.rs
Replace `lazy_static` with `LazyLock`.
Compile time may reduce a little.
See https://github.com/rust-lang-nursery/lazy-static.rs/issues/214
---
> refactor: replace `lazy_static` with `LazyLock`

- Cargo.lock
- Cargo.toml
- crates/ahm/Cargo.toml
- crates/ahm/src/lib.rs
- crates/ahm/src/scanner/data_scanner.rs
- crates/ahm/src/scanner/mod.rs
- crates/ecstore/Cargo.toml
- crates/rio/Cargo.toml
chore: bump workspace dependencies versions
Updated all internal crates under [workspace.dependencies] to the latest patch (0.0.6)
Aligned path-based dependency versions for consistency across the workspace
Prepares for the upcoming release burst
---
> chore: bump workspace dependencies versions

- .github/actions/setup/action.yml
- .github/workflows/build.yml
- Cargo.toml
- build-rustfs.sh
修复在使用 Zig 进行交叉编译时 zstd-sys 包的编译失败问题。
```
error: unable to parse target query 'x86_64-unknown-linux-musl': UnknownOperatingSystem
```
- 将 `mlugg/setup-zig` 更新到 v2（最新稳定版本）
- 指定使用 Zig 0.13.0 版本，该版本对 musl 目标有更好的支持
- 在 Ubuntu 系统依赖中添加 `libzstd-dev` 和 `zstd` 包
- 允许使用系统提供的 zstd 库，避免从源码编译
- 添加 `ZSTD_SYS_USE_PKG_CONFIG=1` 和 `PKG_CONFIG_ALLOW_CROSS=1`
- 为 musl 目标配置正确的 C/C++ 编译器和归档器
- 在 `Cargo.toml` 中为 zstd 添加 `pkg-config` 特性
- 优先使用系统的 zstd 库而不是编译源码
- `.github/actions/setup/action.yml` - 更新 Zig 版本和系统依赖
- `build-rustfs.sh` - 添加环境变量配置
- `.github/workflows/build.yml` - 添加构建环境变量
- `Cargo.toml` - 配置 zstd 依赖特性
这些更改应该能解决：
- ✅ `x86_64-unknown-linux-musl` 目标的编译问题
- ✅ `aarch64-unknown-linux-musl` 目标的编译问题
- ✅ zstd-sys 包的编译稳定性问题
- ✅ 在功能分支上开发
- ✅ 遵循 Conventional Commits 规范
- ✅ 没有直接提交到 main 分支
- ✅ 代码已通过格式化检查
> fix: resolve zstd-sys compilation issues with zig cross-compilation

- .github/actions/setup/action.yml
- .github/workflows/build.yml
- build-rustfs.sh
> fix: Restore working build configuration from 4fb4b353

- .github/workflows/build.yml
- .github/workflows/docker.yml
- Dockerfile
This PR implements a more robust and efficient Docker build triggering mechanism using GitHub's `workflow_run` event, solving critical issues with multi-architecture Docker builds.
- Uses GitHub API to check specific Linux build job status (x86_64 + aarch64)
- Only triggers Docker builds when **both** Linux architectures succeed
- Prevents Docker build failures due to missing ARM64/x86_64 binaries
- **Before**: build.yml → call docker.yml → wait for all platforms (including macOS)
- **After**: build.yml (independent) ← workflow_run ← docker.yml (only waits for Linux)
- Docker builds no longer blocked by macOS/Windows build failures
- Unified use of `TARGETPLATFORM` (linux/amd64, linux/arm64)
- Consistent with Dockerfile.source
- Follows Docker Buildx best practices
- Clear status …
> feat: Implement precise Docker build triggering using workflow_run event

- Dockerfile
This PR fixes a critical bug in the Docker build process where development versions (dev-*) were incorrectly trying to download from the release channel with incorrect filename patterns.
When building Docker images for development versions like , the Dockerfile was:
1. **Incorrectly using release channel**: Trying to download from  path instead of  path
2. **Adding wrong prefix**: Adding  prefix to dev versions (e.g.,  instead of )
3. **Wrong URL construction**: Resulting in 404 errors like:
Instead of the correct:
Enhanced the Dockerfile logic to properly handle different version types:
- **Latest versions**: Use appropriate channel (dev/release) based on CHANNEL parameter
- **Dev versions**: Download from  path without  prefix when 
- **Release versions**: Download from  path with …
> fix: correct Docker build logic for dev version downloads

- .github/workflows/docker.yml
Found inconsistency in short SHA generation between build.yml and docker.yml workflows:
- **build.yml** uses: `git rev-parse --short HEAD` (standard Git approach)
- **docker.yml** used: `cut -c1-7` (forced 7-character truncation)
This inconsistency could lead to version mismatches in edge cases where Git needs more than 7 characters for uniqueness.
- Replace manual `cut -c1-7` with `git rev-parse --short` in docker.yml
- Ensures consistent short SHA length between both workflows
- Git automatically adjusts length for uniqueness, preventing conflicts
- Updated `.github/workflows/docker.yml` line 113 to use Git's standard short SHA generation
- Both workflows now use the same reliable method for generating short commit identifiers
- Verified the change maintains the same 7-character output …
> fix: use consistent short SHA generation across workflows

- .github/workflows/docker.yml
- Dockerfile
Currently, the Docker workflow builds images for all types of builds including development versions (main branch commits, dev-latest, etc.). This creates unnecessary Docker images that are not intended for production use and consumes resources.
This PR modifies both the Docker workflow and Dockerfile to only build images for releases and prereleases, completely removing all development build support:
- **Input Parameters**: 
- Removed `main-latest`, `dev-latest`, and `dev-*` options from manual trigger
- Updated description to only mention supported versions
- Changed default from `main-latest` to `latest`
- **Automatic Builds (workflow_run)**:
- Added filtering logic to skip Docker builds for development versions
- Only tag pushes (releases/prereleases) will trigger Docker image builds
- …
> feat: disable Docker builds for development versions

- .github/workflows/release.yml
The release workflow was failing at the `wait-for-artifacts` step when waiting for build artifacts, specifically for tag `1.0.0-alpha.21`.
The `wait-on-check-action` was receiving the full Git reference `refs/tags/1.0.0-alpha.21` instead of the clean tag name `1.0.0-alpha.21`, causing it to fail to find the corresponding check status.
- Changed `ref` from `${{ github.ref }}` to `${{ needs.release-check.outputs.tag }}`
- This ensures the action receives the clean tag name instead of the full Git reference path
- The `release-check` job already processes and cleans the tag name appropriately
- Build artifacts for `1.0.0-alpha.21` are already available
- After merging this fix, the release workflow should be re-triggered successfully
- ✅ Fixed ref parameter in `wait-for-artifacts` step
- ✅ …
> fix: use correct tag reference in release workflow wait-for-artifacts step

- rustfs/src/storage/ecfs.rs
> fix:getobject range length

- crates/protos/src/lib.rs
This PR optimizes the RPC connection management in the protos library to prevent race conditions and improve connection reuse efficiency.
1. **Improved Connection Retrieval Logic**
- Refactored connection lookup to use a single read lock with `.cloned()` method
- Prevents holding the read lock while performing expensive operations
- Reduces lock contention and improves concurrency
2. **Optimized Connection Caching**
- Fixed race condition where multiple concurrent requests could create duplicate connections
- Ensured new connections are properly cached before being used
- Improved connection reuse efficiency
3. **Better Lock Management**
- Separated read and write operations to minimize lock holding time
- Used block scoping to ensure locks are released promptly
- Reduced potential for …
> fix: optimize RPC connection management and prevent race conditions

- .github/workflows/build.yml
- Dockerfile
- Make Dockerfile version logic robust: always use a single 'v' prefix for versioned releases, regardless of whether RELEASE is '1.0.0' or 'v1.0.0'.
- If RELEASE=latest, keep as 'latest'.
- This prevents double 'v' and ensures correct artifact download.
- Avoids user confusion and download errors when passing different version formats.
- Makes Dockerfile more user-friendly and robust.
- Manually tested with RELEASE=latest, RELEASE=1.0.0, RELEASE=v1.0.0, all download the correct artifact.
---
No breaking changes. No documentation update required.
> fix: robust Dockerfile version logic for v prefix handling

- .github/workflows/build.yml
- 将 latest 文件创建从多个上传步骤统一到构建步骤中
- 确保 OSS 和 GitHub Release 的文件保持一致
- 解决了用户反馈的 latest 文件在 GitHub Release 页面缺失的问题
- 使用 `rustfs-*.zip` glob 匹配替代复杂的临时目录管理
- 减少代码重复，提高可维护性
- 统一文件处理逻辑
- 删除不必要的 dev-latest 和 main-latest 分支区分
- 统一 OSS 上传逻辑，使用简单的 for 循环
- 简化工作流程，减少维护成本
- **文件修改**: 1 个文件 (`.github/workflows/build.yml`)
- **代码变更**: 59 行新增，71 行删除
- **净减少**: 12 行代码，提高了简洁性
- 修复了 latest 文件只上传到 OSS 但不上传到 GitHub Release 的不一致问题
- 消除了构建工作流中的代码重复
- 简化了文件管理和上传逻辑
- 保持了现有的构建矩阵和平台支持
- 确保所有文件生成和上传逻辑的正确性
- 维持了向后兼容性
这个优化将显著提高工作流的可维护性，同时解决用户报告的文件一致性问题。
> refactor: 优化构建工作流，统一 latest 文件处理和简化制品上传

- crates/ecstore/src/disk/local.rs
> fix:#303 returns empty when querying an empty or not dir

- Cargo.toml
update s3s version to solve xml namespace type attribute bug.
---
> fix: update s3s version to solve xml namespace type attribute bug.

- rustfs/src/storage/ecfs.rs
Add etag to  get object response
#307 Unable to use hadoop-aws jar read file on rustfs #307
---
> fix:Add etag to  get object response

- .github/pull_request_template.md
- crates/ahm/src/heal/storage.rs
- crates/config/src/constants/mod.rs
- crates/ecstore/src/set_disk.rs
- crates/ecstore/src/sets.rs
- crates/ecstore/src/store.rs
- crates/notify/Cargo.toml
- crates/utils/src/certs.rs
Change the object integrity verification from reading all data to streaming processing to avoid memory overflow caused by large objects.
Modify the TLS key log check to use environment variables directly instead of configuration constants.
Add memory limits for object data reading in the AHM module.
#369 
---
> refactor(ecstore): Optimize memory usage for object integrity verification

- Dockerfile
- docker-buildx.sh
- Modified Dockerfile to download pre-built binaries from GitHub releases
- For latest releases, use GitHub API to find the correct download URL
- For specific versions, construct the GitHub release URL directly
- Updated docker-buildx.sh script messages to reflect new download source
- This change addresses security concerns about potential tampering with binaries from dl.rustfs.com
---
> feat: change Docker build to download from GitHub releases instead of dl.rustfs.com

- Dockerfile
- RELEASE: GitHub release tag without 'v' prefix (e.g., 1.0.0-alpha.42)
- VERSION: filename version with 'v' prefix (e.g., v1.0.0-alpha.42)
- Download URL uses RELEASE for path, VERSION for filename
- Fixes incorrect URL generation that was adding extra 'v' prefix
---
> fix: separate RELEASE tag and VERSION in Docker build

- .github/workflows/issue-translator.yml
Potential fix for [https://github.com/rustfs/rustfs/security/code-scanning/7](https://github.com/rustfs/rustfs/security/code-scanning/7)
To fix the problem, add a `permissions` block at the workflow level (at the same indentation as `name:` and `on:`), specifying the minimum set of permissions required by the workflow. In this case, the user wanted `contents: read` and `issues: write` (as written, albeit in the wrong place). Remove any invalid `permissions`-like entries (lines 22 and 23) from under the `on:` block, and add a correctly placed `permissions:` block just before or after `on:`. No imports or extra methods are needed for this YAML fix.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 7: Workflow does not contain permissions

- .docker/observability/docker-compose.yml
- .docker/observability/tempo-entrypoint.sh
- docker-compose.yml
- entrypoint.sh
When using the current `docker-compose.yml` file to run rustfs instance in docker container, always show below error:
```
Initializing mount directories: /data/rustfs0 /data/rustfs1 /data/rustfs2 /data/rustfs3 /logs
!!!WARNING: Using default RUSTFS_ACCESS_KEY or RUSTFS_SECRET_KEY. Override them in production!
Starting: /usr/bin/rustfs
Error: Custom { kind: Other, error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }) }
```
After debugging, the error was caused by the `RUSTFS_VOLUMES` env variable.  For `RUSTFS_VOLUME` env variable, the value is `/data/rustfs0,/data/rustfs1,/data/rustfs2,/data/rustfs3`, `entrypoint.sh` script already handle this env var and splits it into four parts and use the new var `LOCAL_VOLUME`, but the final start step still use …
> fix docker compose running with no such file error

- crates/config/src/constants/console.rs
- rustfs/src/main.rs
Adding `RUSTFS_CHECK_UPDATE` environment variable, defaults to `true`. It controls whether to check for newer versions of rustfs.
---
Implements https://github.com/rustfs/rustfs/issues/517
> Adding a toggle for update check

- Cargo.lock
- Cargo.toml
- crates/config/src/observability/config.rs
- crates/obs/Cargo.toml
- crates/obs/src/telemetry.rs
- rustfs/src/server/console.rs
- rustfs/src/server/http.rs
- scripts/run.sh
- Refactor WriteMode selection to ensure all variables moved into thread closures are owned types, preventing lifetime issues.
- Simplify and clarify WriteMode assignment for production and non-production environments.
- Improve code readability and maintainability for logger initialization.
---
> feat(obs): optimize WriteMode selection logic in init_telemetry

- rustfs/src/storage/ecfs.rs
> fix: enforce max-keys limit to 1000 in S3 implementation

- crates/ecstore/src/bucket/replication/replication_resyncer.rs
- crates/ecstore/src/set_disk.rs
- crates/utils/src/path.rs
Issue #625 reported an error when uploading 5GB files via multipart upload:
```
complete_multipart_upload etag err Some("\"2c7ab85a893283e98c931e9511add182\"""), part_id=1
```
This was caused by PR #592, which introduced the `format_etag()` function to ensure HTTP responses comply with RFC 7232 (ETags wrapped in quotes). However, this created a mismatch:
- **UploadPart response** now returns quoted ETag: `"2c7ab85a893283e98c931e9511add182"`
- **Client** submits this quoted ETag in CompleteMultipartUpload request
- **Internal storage** keeps unquoted ETag: `2c7ab85a893283e98c931e9511add182`
- **String comparison fails**: `"etag"` ≠ `etag`
Normalize ETags by removing quotes before comparison using `trim_etag()` function in three critical locations:
1. **CompleteMultipartUpload** …
> fix: normalize ETag comparison in multipart upload and replication
